import 'package:flutter/foundation.dart';

/// Everything that can happen at this table.
///
/// Eleven, from the spec, and the list is closed on purpose: a sealed type
/// means the reducer cannot quietly forget one, and a twelfth verb has to be
/// argued for rather than added.
@immutable
sealed class TableAction {
  const TableAction();
}

/// Moves a card from wherever it is into a pile.
class MoveCard extends TableAction {
  const MoveCard({
    required this.cardId,
    required this.toZoneId,
    this.at,
    this.faceDown,
    this.position,
  });

  final String cardId;
  final String toZoneId;

  /// Where in an ordered pile. Null means the top.
  final int? at;

  /// Null leaves it as it was. Moving to a hand does not turn a card over by
  /// itself, because the table does not know that hands are private: the zone
  /// does, and the screen reads the zone.
  final bool? faceDown;

  final ({double x, double y})? position;
}

class RotateCard extends TableAction {
  const RotateCard(this.cardId);
  final String cardId;
}

class FlipCard extends TableAction {
  const FlipCard(this.cardId);
  final String cardId;
}

class ChangeCounter extends TableAction {
  const ChangeCounter({
    required this.cardId,
    required this.kind,
    required this.by,
  });

  final String cardId;
  final String kind;
  final int by;
}

/// Attaches one card to another, or to nothing. Aura, equipment, energy and
/// evolution are all this.
class AttachCard extends TableAction {
  const AttachCard({required this.cardId, required this.toCardId});

  final String cardId;

  /// Null detaches.
  final String? toCardId;
}

class ShuffleZone extends TableAction {
  const ShuffleZone({required this.zoneId, required this.seed});

  final String zoneId;
  final String seed;
}

class DrawCards extends TableAction {
  const DrawCards({
    required this.fromZoneId,
    required this.toZoneId,
    required this.count,
  });

  final String fromZoneId;
  final String toZoneId;
  final int count;
}

class CreateToken extends TableAction {
  const CreateToken({
    required this.zoneId,
    required this.oracleId,
    required this.cardId,
  });

  final String zoneId;
  final String oracleId;

  /// Generated by the caller rather than inside the reducer, so applying the
  /// same action twice gives the same table. Plan 3 replays these.
  final String cardId;
}

class ChangeLife extends TableAction {
  const ChangeLife({required this.seatId, required this.by});

  final String seatId;
  final int by;
}

class RollDice extends TableAction {
  const RollDice(this.results);

  /// Rolled by the caller for the same reason a token's id is: the reducer has
  /// to be a function, or replaying a game gives a different game.
  final List<int> results;
}

class PassTurn extends TableAction {
  const PassTurn();
}
