import 'package:flutter/foundation.dart';

/// Everything that can happen at this table.
///
/// Ten on the wire. The spec counts eleven and the eleventh is undo, which is
/// a list of whole states on each phone and never travels. The list is closed
/// on purpose: a sealed type means the reducer cannot quietly forget one, and
/// an eleventh verb has to be argued for rather than added.
///
/// Every one of them is a value, and equality is its fields rather than its
/// identity. That is what the wire needs: a verb that came off a wire is a
/// different object from the one that went on, and a table that compares them
/// by identity cannot tell a faithful round trip from a lossy one.
@immutable
sealed class TableAction {
  const TableAction();
}

/// Moves a card from wherever it is into a pile.
class MoveCard extends TableAction {
  const MoveCard({
    required this.cardId,
    required this.toZoneId,
    this.at,
    this.faceDown,
    this.position,
  });

  final String cardId;
  final String toZoneId;

  /// Where in an ordered pile. Null means the top.
  final int? at;

  /// Null leaves it as it was. Moving to a hand does not turn a card over by
  /// itself, because the table does not know that hands are private: the zone
  /// does, and the screen reads the zone.
  final bool? faceDown;

  final ({double x, double y})? position;

  @override
  bool operator ==(Object other) =>
      other is MoveCard &&
      other.cardId == cardId &&
      other.toZoneId == toZoneId &&
      other.at == at &&
      other.faceDown == faceDown &&
      other.position == position;

  @override
  int get hashCode => Object.hash(cardId, toZoneId, at, faceDown, position);
}

/// Turns a card. With no angle it is a toggle, straight to turned and back,
/// which is the tap. With one it sets that angle, which is the menu.
class RotateCard extends TableAction {
  const RotateCard(this.cardId, {this.to});
  final String cardId;
  final int? to;

  @override
  bool operator ==(Object other) =>
      other is RotateCard && other.cardId == cardId && other.to == to;

  @override
  int get hashCode => Object.hash(cardId, to);
}

class FlipCard extends TableAction {
  const FlipCard(this.cardId);
  final String cardId;

  @override
  bool operator ==(Object other) => other is FlipCard && other.cardId == cardId;

  @override
  int get hashCode => cardId.hashCode;
}

class ChangeCounter extends TableAction {
  const ChangeCounter({
    required this.cardId,
    required this.kind,
    required this.by,
  });

  final String cardId;
  final String kind;
  final int by;

  @override
  bool operator ==(Object other) =>
      other is ChangeCounter &&
      other.cardId == cardId &&
      other.kind == kind &&
      other.by == by;

  @override
  int get hashCode => Object.hash(cardId, kind, by);
}

/// Attaches one card to another, or to nothing. Aura, equipment, energy and
/// evolution are all this.
class AttachCard extends TableAction {
  const AttachCard({required this.cardId, required this.toCardId});

  final String cardId;

  /// Null detaches.
  final String? toCardId;

  @override
  bool operator ==(Object other) =>
      other is AttachCard &&
      other.cardId == cardId &&
      other.toCardId == toCardId;

  @override
  int get hashCode => Object.hash(cardId, toCardId);
}

class ShuffleZone extends TableAction {
  const ShuffleZone({required this.zoneId, required this.seed});

  final String zoneId;
  final String seed;

  @override
  bool operator ==(Object other) =>
      other is ShuffleZone && other.zoneId == zoneId && other.seed == seed;

  @override
  int get hashCode => Object.hash(zoneId, seed);
}

class DrawCards extends TableAction {
  const DrawCards({
    required this.fromZoneId,
    required this.toZoneId,
    required this.count,
  });

  final String fromZoneId;
  final String toZoneId;
  final int count;

  @override
  bool operator ==(Object other) =>
      other is DrawCards &&
      other.fromZoneId == fromZoneId &&
      other.toZoneId == toZoneId &&
      other.count == count;

  @override
  int get hashCode => Object.hash(fromZoneId, toZoneId, count);
}

class CreateToken extends TableAction {
  const CreateToken({
    required this.zoneId,
    required this.oracleId,
    required this.cardId,
  });

  final String zoneId;
  final String oracleId;

  /// Generated by the caller rather than inside the reducer, so applying the
  /// same action twice gives the same table. Plan 3 replays these.
  final String cardId;

  @override
  bool operator ==(Object other) =>
      other is CreateToken &&
      other.zoneId == zoneId &&
      other.oracleId == oracleId &&
      other.cardId == cardId;

  @override
  int get hashCode => Object.hash(zoneId, oracleId, cardId);
}

class ChangeLife extends TableAction {
  const ChangeLife({required this.seatId, required this.by});

  final String seatId;
  final int by;

  @override
  bool operator ==(Object other) =>
      other is ChangeLife && other.seatId == seatId && other.by == by;

  @override
  int get hashCode => Object.hash(seatId, by);
}

class RollDice extends TableAction {
  const RollDice(this.results, {this.die});

  /// Rolled by the caller for the same reason a token's id is: the reducer has
  /// to be a function, or replaying a game gives a different game.
  final List<int> results;

  /// Which of them was thrown, as an index into [results].
  ///
  /// The table only keeps where the three dice are resting, so a peer reading
  /// a new set of numbers cannot tell which one moved, and a die that lands on
  /// the number it was already on did not move at all as far as the numbers
  /// are concerned. Somebody watching has to see the die that was thrown turn
  /// over, so the thrower says which.
  ///
  /// Null from a peer built before this existed, and from a replay of one.
  final int? die;

  @override
  bool operator ==(Object other) =>
      other is RollDice &&
      listEquals(other.results, results) &&
      other.die == die;

  @override
  int get hashCode => Object.hash(Object.hashAll(results), die);
}

/// Puts an opening hand back, shuffles, and draws a fresh one.
///
/// One verb and not three, because the three together are the thing a player
/// means and because a hand that went back has to be shuffled in by a seed
/// everybody has: three separate verbs would let a peer see the hand sitting
/// on top of the library between them.
///
/// The London rule is the other half and it is not in here. After the nth
/// mulligan the player puts n cards on the bottom themselves, which is a
/// choice nobody else can make for them and is an ordinary move.
class TakeMulligan extends TableAction {
  const TakeMulligan({required this.seatId, required this.seed});

  final String seatId;

  /// Carried for the same reason ShuffleZone carries one: the reducer has to
  /// be a function, or replaying a game gives a different game.
  final String seed;

  @override
  bool operator ==(Object other) =>
      other is TakeMulligan && other.seatId == seatId && other.seed == seed;

  @override
  int get hashCode => Object.hash(seatId, seed);
}
