import 'dart:math';

/// Names a room is given when it is made, so nobody is ever asked to name
/// one.
///
/// A hundred of them, in the app's own voice: a kitchen table, a few
/// friends, an evening. They are places and occasions rather than adjectives
/// bolted to animals, because the thing being named is where you are playing
/// and the host can see it on the screen they are sharing. The host can type
/// over it; an empty box asking for a name is the thing this exists to stop.
///
/// Two words at most, no punctuation past an apostrophe, nothing that needs
/// explaining when it is read out over a call.
const roomNames = <String>[
  'The Kitchen Table',
  'The Back Room',
  'Sunday Night',
  'Friday Night',
  'Saturday Table',
  'The Long Table',
  'The Side Table',
  'The Card Table',
  'The Good Table',
  'The Corner Booth',
  'The Window Seat',
  'The Front Porch',
  'The Back Porch',
  'The Garage',
  'The Attic',
  'The Basement',
  'The Spare Room',
  'The Dining Room',
  'The Living Room',
  'The Study',
  'The Library',
  'The Den',
  'The Lounge',
  'The Workshop',
  'The Shed',
  'The Greenhouse',
  'The Loft',
  'The Landing',
  'The Hallway',
  'The Pantry',
  'The Cellar',
  'The Terrace',
  'The Balcony',
  'The Courtyard',
  'The Garden',
  'The Allotment',
  'The Orchard',
  'The Rooftop',
  'The Fire Escape',
  'The Driveway',
  'Second Breakfast',
  'Late Coffee',
  'Cold Pizza',
  'Leftovers',
  'One More Round',
  'Last Orders',
  'Extra Innings',
  'Overtime',
  'The Rematch',
  'The Decider',
  'House Rules',
  'Open Invitation',
  'Everyone Welcome',
  'Bring A Chair',
  'Pull Up A Chair',
  'Room For One More',
  'Mind The Step',
  'Shoes Off',
  'Help Yourself',
  'Put The Kettle On',
  'The Usual',
  'The Regulars',
  'Same Time Tuesday',
  'Every Other Thursday',
  'The Standing Game',
  'The Long Game',
  'The Quiet Game',
  'The Loud Game',
  'The Slow Game',
  'The Short Game',
  'The Friendly',
  'No Takebacks',
  'Shuffle Up',
  'Cut The Deck',
  'Deal Me In',
  'Draw Step',
  'Upkeep',
  'End Step',
  'Top Deck',
  'The Mulligan',
  'The Sideboard',
  'The Scry',
  'The Stack',
  'The Graveyard Shift',
  'Mana Burn',
  'Land Drop',
  'The Commons',
  'The Foil',
  'The Misprint',
  'Sleeved Up',
  'Table Talk',
  'The Pod',
  'The Playgroup',
  'Four Chairs',
  'Three Chairs',
  'The Round Table',
  'The Old Table',
  'The New Table',
  'The Far Table',
  'The Near Table',
  'Somebody\'s Kitchen',
];

final _random = Random();

/// One of [roomNames], at random. What the name box opens holding.
String freshRoomName() => roomNames[_random.nextInt(roomNames.length)];
